### ISSUE TITLE
[Bug] materialized view failed to compile and re-run after upgrading to 1.7.4

### ISSUE THREAD

**Issue by usmift** [dbt-labs/dbt-bigquery#1108]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

14:32:07    Compilation Error in model mymodel (models/mymodel.sql)
  unhashable type: 'dict'
  
  > in macro get_materialized_view_configuration_changes (macros/relations/materialized_view/alter.sql)
  > called by macro materialized_view_get_build_sql (macros/materializations/models/materialized_view.sql)
  > called by macro materialization_materialized_view_default (macros/materializations/models/materialized_view.sql)
  > called by model mymodel (models/mymodel.sql)

### Expected Behavior

Should re-run without any errors

### Steps To Reproduce

1. Create a model as "materialized_view"
2. Run the model it will work for the first time
3. Rerun and it will throw error
```
 {{
  config(
    materialized = 'materialized_view',
    )
}}

select * from {{ ref('orders') }}
```

### Relevant log output

```shell
14:32:07    Compilation Error in model mymodel (models/mymodel.sql)
  unhashable type: 'dict'
  
  > in macro get_materialized_view_configuration_changes (macros/relations/materialized_view/alter.sql)
  > called by macro materialized_view_get_build_sql (macros/materializations/models/materialized_view.sql)
  > called by macro materialization_materialized_view_default (macros/materializations/models/materialized_view.sql)
  > called by model mymodel (models/mymodel.sql)
```

### Environment

```markdown
- OS: MacOS Ventura 13.6
- Python: 3.9.11
- dbt-core: 1.7.4
- dbt-bigquery: 1.7.4
```

**Comment by i-kounakis** [comment]
Hello, is there any chance we can reopen this issue? 🙇
